#!/usr/bin/python
# -*- coding: UTF-8 -*-

from os import system, name
import itertools
import threading
import time
import sys
import datetime
from base64 import b64decode,b64encode
from datetime import date


expirydate = datetime.date(2021, 9, 24)
#expirydate = datetime.date(2021, 8, 30)
today=date.today()
def hero():

    def chalo():
        done = False
        #here is the animation
        def animate():
            for c in itertools.cycle(['|', '/', '-', '\\']) :
                if done:
                    break
                sys.stdout.write('\rhacking in the Bcone server for next colour--------- ' + c)
                sys.stdout.flush()
                time.sleep(0.1)
            sys.stdout.write('\rDone!     ')

        t = threading.Thread(target=animate)
        t.start()

        #long process here
        time.sleep(20)
        done = True

    def chalo1():
        done = False
        #here is the animation
        def animate():
            for c in itertools.cycle(['|', '/', '-', '\\']):
                if done:
                    break
                sys.stdout.write('\rgetting the colour wait --------- ' + c)
                sys.stdout.flush()
                time.sleep(0.1)
            sys.stdout.write('\rDone!     ')

        t = threading.Thread(target=animate)
        t.start()

        #long process here
        time.sleep(20)
        done = True

    def clear():
        # for windows
        if name == 'nt':
            _ = system('cls')
        # for mac and linux(here, os.name is 'posix')
        else:
            _ = system('clear')
    def getSum(n):
        sum=0
        for digit in str(n):
            sum+= int(digit)
        return sum+1

    def lawde_time_pe_khel(n):
        check=0
        for digit in (n):
            if(int(digit)==0):
                check=check+1
        return check
    clear()
    y=1
    clear()
    newperiod=period
    banner='figlet IDFC Bcone|lolcat'
    numbers=[]
    while(y):
        clear()
        banner='figlet IDFC Bcone|lolcat'
        system(banner)
        print("Contact me on telegram @IDFCMONEY"|lolcat)
        print("Enter ",newperiod," Bcone Price :"|lolcat)
        current=input()
        current=int(current)
        chalo()
        print("\n---------Successfully hacked the server-----------"|lolcat)
        chalo1()
        print("\n---------Successfully got the colour -------------"|lolcat)
        print('\n')
        last2=str(current)[-2:]
        samjha_maadarchod=lawde_time_pe_khel(last2)
        if(newperiod%2==0):
            sum=getSum(current)
            if(sum%2==0):
                print(newperiod+1," : 🔴, RED"|lolcat)
            else:
                print(newperiod+1,"  : 🟢, GREEN"|lolcat)
        else:
            sum=getSum(current)
            if(sum%2==0):
                print(newperiod+1,"   : 🔴, RED"|lolcat)
            else:
                print(newperiod+1,"   : 🟢, GREEN"|lolcat)
        newperiod+=1
        numbers.append(current)
        y=input("Do you want to play : Press 1 and 0 to exit \n"|lolcat)
        if(y==0):
            y=False
        if (len(numbers)>11):
            clear()
            system('figlet Thank You!!|lolcat')
            print("Play on next specified time!!"|lolcat)
            print("-----------Current Time UP----------"|lolcat)
            sys.exit(" \n \n \n Contact on Telegram @IDFCMONEY"|lolcat)
            #print(numbers)
  



if(expirydate>today):
    now = datetime.datetime.now()
    First = now.replace(hour=13, minute=55, second=0, microsecond=0)
    Firstend = now.replace(hour=14, minute=35, second=0, microsecond=0)
    Second = now.replace(hour=16, minute=25, second=0, microsecond=0)
    Secondend = now.replace(hour=17, minute=35, second=0, microsecond=0)
    Third = now.replace(hour=15, minute=55, second=0, microsecond=0)
    Thirdend = now.replace(hour=16, minute=35, second=0, microsecond=0)
    Final = now.replace(hour=17, minute=55, second=0, microsecond=0)
    Finalend = now.replace(hour=18, minute=35, second=0, microsecond=0)

    if (now>Third and now<Thirdend):
            period=320
            hero()
    elif(now):
            period=340
            hero()
    elif(False):
            period=340
            hero()
    elif(False):
            period=360
            hero()
    else:
        banner='figlet IDFC Bcone|lolcat'
        system(banner)
        print("Hi!! Thanks for buying the hack"|lolcat)
        #print("Hi! thanks for trying our DEMO"|lolcat)
        print("----------Your play time-----------"|lolcat)
        #print("31st Aug 2021, 11:00 AM- 11:30 AM"|lolcat)
        #print("31st Aug 2021, 02:00 PM- 02:30 PM"|lolcat)
        print("12th Dec 2021, 04:00 PM- 04:30 PM"|lolcat)
        #print("31st Aug 2021, 08:00 PM- 08:30 PM"|lolcat)
        print("Please play on the given time, and "|lolcat)
        print("If you think it is an error contact"|lolcat)
        print(" admin on telegram @IDFCMONEY "|lolcat)



else:
    def clear():
        # for windows
        if name == 'nt':
            _ = system('cls')
        # for mac and linux(here, os.name is 'posix')
        else:
            _ = system('clear')
    code="PROFIT
    test="LOLISLIFE"
    night="LIFEISLOL"
    nextday="FUCK"
    banner='figlet IDFC Bcone|lolcat'
    rava=0
    now = datetime.datetime.now()
    Second = now.replace(hour=10, minute=55, second=0, microsecond=0)
    Secondend = now.replace(hour=14, minute=55, second=0, microsecond=0)
    Third = now.replace(hour=15, minute=30, second=0, microsecond=0)
    Thirdend = now.replace(hour=18, minute=34, second=0, microsecond=0)
    Final = now.replace(hour=18, minute=35, second=0, microsecond=0)
    Finalend = now.replace(hour=22, minute=35, second=0, microsecond=0)

    if(now>Second and now<Secondend):
            rava=0
    elif(now>Third and now<Thirdend):
            rava=300
    elif(now>Final and now<Finalend):
            rava=410
    system(banner)
    print-------*----------*-------------*----------*"|lolcat)
    print("To Know The Password --- Contact me"|lolcat)
    print(" on telegram ----@IDFCMONEY "|lolcat)
    print(" Recharge Amount :        Total limit "|lolcat )
    print(" 1.     1000 INR -------  1 Day (10 Games)"|lolcat)
    print(" 2.     5000 INR -------  7 Days(50 Games)"|lolcat)
    print("*---------*----------*--------*---------*--------*"|lolcat)
    print("Your custom hack can be made request from us."|lolcat)
    print("Beware of fraudsters!!!"|lolcat)
    while(True):
        print("*--------*--------*-------*---------*---------*"|lolcat)
        print("Hi, IDFC Here"|lolcat)
        print("If you send Payment to any other Person On Telegram ,"|lolcat)
        print(" then IT IS A SCAMMM"|lolcat)
        print("Send payment only to IDFC "|lolcat)
        print("Only I Have Hack , Others Only Scam"|lolcat)
        print("Don't Believe Any One Who Says "|lolcat)
        print("I Have Hack And Sends You Only "|lolcat)
        print("Fake ScreenShots Or Edited Ones"|lolcat)
        print("For Payments Message Me Before Sending "|lolcat)
        print("*---------*----------*-------------*----------*"|lolcat)
        
        print("            Things Under Maintenence           "|lolcat)      
        print("Automatic Recharge :  Under Maintenence"|lolcat)
        print("Please Ignore Play Timings They Are Under Maintenence"|lolcat)
        print("*---------*----------*-------------*----------*"|lolcat)
        
        
        print("Enter Correct activation code for Opening Hack "|lolcat)
        bhai=input(": "|lolcat)
        if(bhai==code or bhai==test):
            clear()
            banner='figlet IDFC Bcone|lolcat'
            system(banner)
            print("----------Your play time-----------"|lolcat)
            print("13th Dec 2021, 02:30 PM- 03:00 PM"|lolcat)
            print("13th Dec 2021, 05:30 PM- 06:00 PM"|lolcat)
            print("13th Dec 2021, 08:30 PM- 09:00 PM"|lolcat)
            print("Please play on the given time, and "|lolcat)
            print("If you think it is an error contact"|lolcat)
            print("me on telegram @IDFCMONEY"|lolcat)
            print("*---------*----------*-------------*----------*"|lolcat)
            print("...............Booting Hack ................."|lolcat)
            time.sleep(20)
            period=0
            hero()
            #print("Today Server is off because I am out "|lolcat)
            #rint(" of town, Tomorrow It will work as usual."|lolcat)
            #print(" Thank You!!"|lolcat)
            #rint("To all the weekly members next week, cost will be  "|lolcat)
            #print(" 4000 INR , because in this week 2 days off " |lolcat)
            #print("Thank You!! "|lolcat)
            sys.exit(" \n \n \n Contact on Telegram @IDFCMONEY"|lolcat)
        elif(bhai==nextday):
            clear()
            banner='figlet IDFC Bcone|lolcat'
            system(banner)
            print("----------Your play time-----------"|lolcat)
            print("1st-30th Dec 2021, 02:30 PM- 03:00 PM"|lolcat)
            print("1st-30th Dec 2021, 06:00 PM- 06:30 PM"|lolcat)
            print("1st-30th Dec 2021, 08:30 PM- 09:00 PM"|lolcat)
            print("Please play on the given time, and "|lolcat)
            print("If you think it is an error contact"|lolcat)
            print("*---------*----------*-------------*----------*"|lolcat)
            print("...............Booting Hack ................."|lolcat)
            time.sleep(20)
            period=300
            hero()
            #period("Sorry too many people(>20) using hack in same time "|lolcat)
            sys.exit(" \n \n \n Contact on Telegram @IDFCMONEY"|lolcat)
        elif(bhai==night):
            clear()
            banner='figlet IDFC Bcone|lolcat'
            system(banner)
            print("----------Your play time-----------"|lolcat)
            print("10th Dec 2021,  08:30 PM- 09:00 PM"|lolcat)
            print("11th Dec 2021, 08:30 PM- 09:00 PM"|lolcat)
            print("12th Dec 2021, 08:30 PM- 09:00 PM"|lolcat)
            print("Please play on the given time, and "|lolcat)
            print("If you think it is an error contact"|lolcat)
            print("*---------*----------*-------------*----------*"|lolcat)
            print("...............Booting Hack ................."|lolcat)
            time.sleep(20)
            period=410
            hero()
            sys.exit(" \n \n \n Contact on Telegram @IDFCMONEY"|lolcat)
        else:
            clear()
            banner='figlet IDFC Bcone|lolcat'
            system(banner)
            print("Incorrect Activation Code :")
     
  
